openapi: 3.0.3
info:
  title: Curriculum API
  description: |-
    This API manages curriculums and provides configuration and health check endpoints.
  contact:
    email: devs@agile-learning.institute
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
paths:
  /api/curriculum/{id}:
    get:
      summary: Get a curriculum by ID
      operationId: getCurriculumById
      tags:
        - Curriculum
      parameters:
        - name: id
          in: path
          description: ID of the curriculum to retrieve
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Curriculum'
        '404':
          description: Curriculum not found
    patch:
      summary: Update a curriculum by ID
      operationId: updateCurriculumById
      tags:
        - Curriculum
      parameters:
        - name: id
          in: path
          description: ID of the curriculum to update
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        description: Updated curriculum data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Curriculum'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Curriculum'
        '404':
          description: Curriculum not found
        '400':
          description: Invalid request data
  /api/config/:
    get:
      summary: Get API Configuration Information
      operationId: getConfig
      tags:
        - Configuration
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Config'
  /api/health/:
    get:
      summary: Prometheus Healthcheck endpoint
      operationId: getHealth
      tags:
        - Health
      responses:
        '200':
          description: Successful operation
components:
  schemas:
    Curriculum:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: The unique identifier for a curriculum
        name:
          type: string
          description: The name of the curriculum
        description:
          type: string
          description: Description of the curriculum
        content:
          type: string
          description: Content of the curriculum
    Config:
      type: object
      properties:
        apiVersion:
          type: string
          description: Semantic Version Number
        someConfig:
          type: string
          description: Some configuration option
