openapi: 3.0.3
info:
  title: Curriculum API
  description: |
    This API manages the curriculum for apprentices, providing endpoints to add, update, and retrieve learning resources.
  contact:
    email: devs@agile-learning.institute
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
paths:
  /api/curriculum/{id}:
    get:
      summary: Get or create a curriculum
      description: |
        If the curriculum with the given ID exists, retrieves it. If not, a new curriculum will be created with the provided ID.
      operationId: getOrCreateCurriculum
      parameters:
        - name: id
          in: path
          description: ID of curriculum to retrieve or create
          required: true
          schema:
            type: string
            format: GUID
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Curriculum'
        '500':
          description: A Processing Error occured
    post:
      summary: Add a Resource to a curriculum
      description: |
        Adds a new Respirce to the curriculum with the provided ID.
      operationId: addResourceToCurriculum
      parameters:
        - name: id
          in: path
          description: ID of the curriculum
          required: true
          schema:
            type: string
            format: GUID
      requestBody:
        description: Resource details to add to the curriculum
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Resource'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resource'
        '500':
          description: A processing error has occured

  /api/curriculum/{id}/{seq}:
    patch:
      summary: Update an existing curriculum
      description: |
        Updates an existing curriculum with the provided ID. If the curriculum does not exist, a new one will not be created.
      operationId: updateCurriculum
      parameters:
        - name: id
          in: path
          description: ID of curriculum to update
          required: true
          schema:
            type: string
            format: GUID
        - name: seq
          in: path
          description: Sequence of Resource to update
          required: true
          schema:
            type: number
      requestBody:
        description: Updated Resource details
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Resource'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resource'
        '500':
          description: A processing error has occured
    delete:
      summary: Delete a Resource from a curriculum
      description: |
        Deletes the Resource with the provided Sequence from the curriculum.
      operationId: deleteResourceFromCurriculum
      parameters:
        - name: id
          in: path
          description: ID of curriculum to update
          required: true
          schema:
            type: string
            format: GUID
        - name: seq
          in: path
          description: Sequence of Resource to update
          required: true
          schema:
            type: number
      responses:
        '204':
          description: Resource successfully deleted
        '500':
          description: A processing error has occured

  /api/config/:
    get:
      summary: Get API Configuration Information
      description: |
        Retrieves information about the API's configuration.
      operationId: getConfig
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Config'

  /api/health/:
    get:
      summary: Health Check Endpoint
      description: |
        Retrieves information about the health status of the API.
      operationId: healthCheck
      responses:
        '200':
          description: Successful operation

components:
  schemas:
    Curriculum:
      type: object
      properties:
        _id:
          description: The unique identifier for a curriculum
          type: string
          format: UUID
        resources:
          description: An array of resources within the curriculum
          type: array
          items:
            $ref: '#/components/schemas/Resource'
      additionalProperties: false

    Resource:
      type: object
      properties:
        sequence:
          description: Sequence for ordering
          type: number
        roadmap:
          description: roadmap status - now/next/later/celebrated
          enum:
            - Completed
            - Now
            - Next
            - Later
          type: string
        path:
          description: A path to group segments
          pattern: ^[ -~]{0,256}$
          type: string
        segment:
          description: A segment to group topics
          pattern: ^[ -~]{0,256}$
          type: string
        topic:
          description: A topic to group resources
          pattern: ^[ -~]{0,256}$
          type: string
        type:
          description: resource type - Resource or Adhoc
          enum:
            - Resource
            - Adhoc
          type: string
        resource_id:
          description: resource id for topic resources
          type: string
        resource_name:
          description: resource name for adHoc resources
          pattern: ^[ -~]{0,256}$
          type: string
        resource_url:
          description: resource link for adHoc resources
          pattern: >-
            ^(https?:\/\/)([a-zA-Z0-9-]{1,63}\.)+[a-zA-Z-]{2,24}(:[0-9]{1,5})?(\/(([\w\-\.~]|%[a-fA-F0-9]{2}|[!\$&'\(\)\*\+,;=:@])*\/?)*)?
          type: string
        started:
          description: When did they start this resource
          type: string
        completed:
          description: resource short name
          type: string
        rating:
          description: resource short name
          type: number
        review:
          description: resource short name
          pattern: ^[ -~]{0,256}$
          type: string
      additionalProperties: false

    Config:
      type: object
      properties:
        apiVersion:
          type: string
          description: Semantic Version Number
        configItems:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                description: Conf Item Name (Env Var Name, File Name)
              value:
                type: string
                description: The value for that config item
              from:
                type: string
                description: Where the value was found
                enum:
                  - default
                  - environment
                  - file
